version: '3.8'

services:
  frontend:
    image: nginx:alpine
    volumes:
      - ./frontend:/usr/share/nginx/html:ro
    networks:
      - frontend_network
    ports:
      - "80:80"

  backend:
    build: ./backend
    environment:
      - DATABASE_URL=postgres://postgres:example@database/postgres
    networks:
      - frontend_network
      - backend_network
    depends_on:
      - database
    ports:
      - "3000:3000"

  database:
    image: postgres:alpine
    environment:
      POSTGRES_PASSWORD: example
    networks:
      - backend_network

networks:
  frontend_network:
    driver: bridge
  backend_network:
    driver: bridge
